How to solve equation

$Ax = b$

$A$ - matrix;
$x$ - vector;
$b$ - vector

In [1]:
import numpy as np
from numpy.linalg import solve

A = np.array([[1,2,3], [22, 32, 42], [55, 66, 100]])
b = np.array([1,2,3])
x = solve(A, b)
x

array([-1.4057971 , -0.1884058 ,  0.92753623])

How to find inverse matrix

In [2]:
import numpy as np
from numpy.linalg import inv
A = np.array([[1,2,3], [22, 32, 42], [55, 66, 100]])
np.dot(inv(A), A)


array([[ 1.00000000e+00, -4.30211422e-16, -1.08246745e-15],
       [-1.94289029e-16,  1.00000000e+00, -9.99200722e-16],
       [ 9.71445147e-17,  4.71844785e-16,  1.00000000e+00]])

In [3]:
import numpy as np
from numpy.linalg import eig
I = np.array([[2./3, -1./4], [-1./4, 2./3]])
Es, evectors = eig(A)
print(Es)
print(evectors)

[130.28974561  -0.6335219    3.34377629]
[[ 0.0274338   0.82101394  0.00991786]
 [ 0.3979758   0.15403247 -0.82841589]
 [ 0.91698563 -0.5497364   0.56002567]]


In [4]:
import numpy as np
Vec = np.array([evectors[0, 0], evectors[1, 0]])
LHS = np.dot(I, Vec)
RHS = Es[0]*Vec
print(LHS)
print(RHS)

[-0.08120475  0.25845875]
[ 3.57434229 51.85216565]


In [5]:
#1
import numpy as np
from numpy.linalg import inv, det
A = np.matrix([
    [4, -2, 1],
    [3, 6, -4],
    [2, 1, 8]
])
A_inv = inv(A)
#a
print(np.matmul(A_inv, A))
print(np.matmul(A,A_inv))

print(det(A))

[[ 1.00000000e+00 -3.46944695e-18  5.55111512e-17]
 [ 2.77555756e-17  1.00000000e+00  2.22044605e-16]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  6.93889390e-18  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]]
262.99999999999983


In [8]:
#2 Ax = b
from numpy.linalg import solve
b1 = np.array([12, -25, 32])
b2 = np.array([4, -1, 22])
b3 = np.array([20, -30, 40])
A = np.matrix([
    [4, -2, 1],
    [3, 6, -4],
    [2, 1, 8]
])
x1 = solve(A, b1)
x2 = solve(A, b2)
x3 = solve(A, b3)
print(x1)
print(x2)
print(x3)

[ 1. -2.  4.]
[0.89353612 0.98859316 2.40304183]
[ 2.31939163 -2.96577947  4.79087452]


In [11]:
#3
from numpy.linalg import eig
A = np.array([
    [7, 5],
    [-5, 7]
])
Es, evectors = eig(A)
print(Es)
print(evectors)

[7.+5.j 7.-5.j]
[[0.        -0.70710678j 0.        +0.70710678j]
 [0.70710678+0.j         0.70710678-0.j        ]]


In [16]:
#1.2.3
from sympy import *
x, y = symbols('x y')

y = diff(tan(x), x)

y = diff(5*x**4 + 7*x**2, x, 1)
print(y)

y = diff(5*x**4 + 7*x**2, x, 2)
print(y)

x, y = symbols('x y')
z = (x + y)**8
expand(z)

sin(x).series(x, 0)
sin(x).series(x, 10)
z = 1/cos(x)
z.series(x, 0)

factor(x**2 - 1)

20*x**3 + 14*x
2*(30*x**2 + 7)


1 + x**2/2 + 5*x**4/24 + O(x**6)

In [4]:
import numpy as np
# float machine precision
eps = 1.
N = 10000
for i in range(N):
    eps = eps/2.
    one = 1. + eps
    if one == 1.:
        print(one)
        print(f"iteration: {i}")
        print(f"eps: {eps}")
        break

# complex numbers machine precision
eps = 1.0j
N = 10000
for i in range(N):
    eps = eps/2.
    one = 1.0j + eps
    if one == 1.0j:
        print(one)
        print(f"iteration: {i}")
        print(f"eps: {eps}")
        break

1.0
iteration: 52
eps: 1.1102230246251565e-16
1j
iteration: 52
eps: 1.1102230246251565e-16j
