In [1]:
import numpy as np
from numpy.linalg import solve

A = np.array([[1,2,3], [22, 32, 42], [55, 66, 100]])
b = np.array([1,2,3])
x = solve(A, b)
x

array([-1.4057971 , -0.1884058 ,  0.92753623])

In [2]:
from numpy.linalg import inv
np.dot(inv(A), A)


array([[ 1.00000000e+00, -4.30211422e-16, -1.08246745e-15],
       [-1.94289029e-16,  1.00000000e+00, -9.99200722e-16],
       [ 9.71445147e-17,  4.71844785e-16,  1.00000000e+00]])

In [3]:
from numpy.linalg import eig
I = np.array([[2./3, -1./4], [-1./4, 2./3]])
I
Es, evectors = eig(A)
print(Es)
print(evectors)

[130.28974561  -0.6335219    3.34377629]
[[ 0.0274338   0.82101394  0.00991786]
 [ 0.3979758   0.15403247 -0.82841589]
 [ 0.91698563 -0.5497364   0.56002567]]


In [4]:
Vec = np.array([evectors[0, 0], evectors[1, 0]])
LHS = np.dot(I, Vec)
RHS = Es[0]*Vec
print(LHS)
print(RHS)

[-0.08120475  0.25845875]
[ 3.57434229 51.85216565]


In [6]:
#1
from numpy.linalg import inv, det
A = np.matrix([
    [4, -2, 1],
    [3, 6, -4],
    [2, 1, 8]
])
A_inv = inv(A)
#a
print(np.matmul(A_inv, A))
print(np.matmul(A,A_inv))

print(det(A))

[[ 1.00000000e+00 -3.46944695e-18  5.55111512e-17]
 [ 2.77555756e-17  1.00000000e+00  2.22044605e-16]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00  6.93889390e-18  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]]
262.99999999999983


In [8]:
#2 Ax = b
from numpy.linalg import solve
b1 = np.array([12, -25, 32])
b2 = np.array([4, -1, 22])
b3 = np.array([20, -30, 40])
A = np.matrix([
    [4, -2, 1],
    [3, 6, -4],
    [2, 1, 8]
])
x1 = solve(A, b1)
x2 = solve(A, b2)
x3 = solve(A, b3)
print(x1)
print(x2)
print(x3)

[ 1. -2.  4.]
[0.89353612 0.98859316 2.40304183]
[ 2.31939163 -2.96577947  4.79087452]


In [11]:
#3
from numpy.linalg import eig
A = np.array([
    [7, 5],
    [-5, 7]
])
Es, evectors = eig(A)
print(Es)
print(evectors)

[7.+5.j 7.-5.j]
[[0.        -0.70710678j 0.        +0.70710678j]
 [0.70710678+0.j         0.70710678-0.j        ]]


In [16]:
#1.2.3
from sympy import *
x, y = symbols('x y')

y = diff(tan(x), x)

y = diff(5*x**4 + 7*x**2, x, 1)
print(y)

y = diff(5*x**4 + 7*x**2, x, 2)
print(y)

x, y = symbols('x y')
z = (x + y)**8
expand(z)

sin(x).series(x, 0)
sin(x).series(x, 10)
z = 1/cos(x)
z.series(x, 0)

factor(x**2 - 1)

20*x**3 + 14*x
2*(30*x**2 + 7)


1 + x**2/2 + 5*x**4/24 + O(x**6)

In [43]:
#Differentiation
ta = [0.1, 1.0, 100.0]
h = 0.000000000000039
def make_forward_diff(func, ta, h):
    for t in ta:
        val = (func(t+h) - func(t))/h
        print(val)

def make_central_diff(func, ta, h):
    for t in ta:
        val = (func(t+h/2) - func(t-h/2))/h
        print(val)

print("forward:")
make_forward_diff(np.cos, ta, h)
make_forward_diff(np.exp, ta, h)
print("central:")
make_central_diff(np.cos, ta, h)
make_central_diff(np.exp, ta, h)

forward:
-0.10248212535001446
-0.8454775341376193
0.5551115123125783
1.1045295732168225
2.7328566760003854
2.93296563153767e+43
central:
-0.09963539964584739
-0.8454775341376193
0.3672276158375518
1.1045295732168225
2.7214697731837174
1.9553104210251136e+43


In [ ]:
###### 